### PR TITLE
Update 2020-10-12-Introduction-to-JavaScript.md

### PR DESCRIPTION
**Pull request by amandewatnitrr**
**Introduction to JavaScript** <br/>
Aman Kumar Dewangan(AkD)

**The Blog is for those who are beginners into Web Development and have already learned HTML and CSS and wish to learn Javascript in order to make their website more responsive.** <br/>

My name is Aman Kumar Dewangan, currently pursuing my B.Tech in Electrical Engineering at the National Institute of Technology Raipur. I am a proficient IoT Developer, Electronics Enthusiast, worked with no. of Micro-controllers including Arduino and Raspberry Pi. I am also a Frontend Developer and beginner in Cloud Engineering. I have recently started working on Open-Source and generally program in C++. I have participated in many Hackathons as well.

- [x] I've read and complied with the rules mentioned in the `Readme.md`.

### CODE REVIEW

**Comment by priyanshisharma** [comment]
What is the update about?

**Review by priyanshisharma — COMMENTED** [review]
What is the update about?

I see 12 additions and 13 deletions which looks like a minor update, and we're bound to have 1 PR per blog in order to maintain the quality of hacktoberfest PRs, still if it is something major/important we can consider merging upto 2 PRs. So please explain why is this required? and also please make sure that this is the final update.

**Review by ExpressHermes — COMMENTED** [review]
@amandewatnitrr Make sure to give meaningful message for each commit. The message should tell us about the changes/improvements you have done in code

**Comment by amandewatnitrr** [comment]
I have replaced the Alt with <image> tag

**Comment by priyanshisharma** [comment]
Okay, and why do we need that update? 😅

**Comment by amandewatnitrr** [comment]
cause images are not visible over the blog, as the links are hard coded

**Comment by priyanshisharma** [comment]
The links are still _hard-coded_ with the tags I suppose 😅

**Comment by amandewatnitrr** [comment]
okhhh, suggest me proper changes accordingly

**Comment by priyanshisharma** [comment]
@amandewatnitrr I think the issue you were facing has been solved in the last 2 commits, check them out.

Hard-coding means to add the *exact url* , it doesn't matter if it is done in html or markdown.
Since this is a Jekyll blog, the format is of the address it `{{site.baseurl}}/assets/image.png`, where `{{site.baseurl}}` is the base url, and not hardcoded.

We understand that we had not added instructions to add images, and since this was a content based task its totally okay to not get this in your PR.

The following readings might help you understand what was required

* https://talk.jekyllrb.com/t/i-cannot-get-an-image-to-display/850
* https://jekyllrb.com/docs/posts/

Feel free to comment your doubts, or reopen the PR if you believe that it is required.

**Review by priyanshisharma — COMMENTED** [review]
@amandewatnitrr I think the issue you were facing has been solved in the last 2 commits, check them out.

Hard-coding means to add the *exact url* , it doesn't matter if it is done in html or markdown.
Since this is a Jekyll blog, the format is of the address it `{{site.baseurl}}/assets/image.png`, where `{{site.baseurl}}` is the base url, and not hardcoded.

We understand that we had not added instructions to add images, and since this was a content based task its totally okay to not get this in your PR.

The following readings might help you understand what was required

* https://talk.jekyllrb.com/t/i-cannot-get-an-image-to-display/850
* https://jekyllrb.com/docs/posts/

Feel free to comment your doubts, or reopen the PR if you believe that it is required.

**Pull request closed without merging**
