### PR TITLE
Article on "Functions and Scope Chaining in JavaScript"

### PR DESCRIPTION
**Pull request by amandewatnitrr**
**Functions and Scope Chaining in JavaScript** <br/>
Aman Kumar Dewangan(AkD)

**The Blog is in Continuation to the previous blog on "Adding Basic Complexity To Javascript", here we introduce you to the functions in JavaScript and Scope Chaining in JavaScript.** <br/>

My name is Aman Kumar Dewangan, currently pursuing my B.Tech in Electrical Engineering at the National Institute of Technology Raipur. I am a proficient IoT Developer, Electronics Enthusiast, worked with no. of Micro-controllers including Arduino and Raspberry Pi. I am also a Frontend Developer and beginner in Cloud Engineering. I have recently started working on Open-Source and generally program in C++. I have participated in many Hackathons as well.

- [x] I've read and complied with the rules mentioned in the `Readme.md`.

### CODE REVIEW

**Review by ExpressHermes — COMMENTED** [review]
@amandewatnitrr We will keep this PR open and you can make further commits to it until you have completed this blog as a whole. You are opening new PRs for every new addition to blog which is a bad practice. Keep working on this and when you finish the blog, ping the Maintainers and we will review and merge it.

**Comment by amandewatnitrr** [comment]
It's actually the whole JavaScript Tutorial, in order to keep the readers engaged it has been broken down to 10 modules, alongside 3 fun minor projects soon coming up. This blog is complete in itself.
If you would like I can share the topics discussed in each module.

**Comment by ExpressHermes** [comment]
You can add a table of content. This PR will be merged when you have completed all the 10 modules.

**Comment by amandewatnitrr** [comment]
Please provide me some guidelines for the table of content should I Attach it with my first article or a new one

**Comment by ExpressHermes** [comment]
In next commit, add a table of content in the first article.

**Comment by amandewatnitrr** [comment]
Okay, so I had a plan, from my side I will add a table and along with it the blogs up to the first minor project, that will be 1 pull request means this on, so don't close this one, review and merge it after I bring all blogs up to 1st minor project.

**Comment by amandewatnitrr** [comment]
The Minor project in itself would be a pull request as it is quite difficult and lengthy and then I will be continuing with further tutorials.

**Pull request closed without merging**
